name: gmail-headline
version: git
summary: Inbox headline in Gmail
description: |
  gmail-headline retrieves and store emails header and digest of body from Gmail.

confinement: devmode
base: core18

parts:
  gmail-headline:
    plugin: go
    go-importpath: github.com:ryumei/gmail-headline
    source: .
    source-type: git
    build-packages:
      - gcc

apps:
  gmail-headline:
    command: bin/gmail-headline

